#!/bin/sh
### BEGIN INIT INFO
# Provides:          rootfs-resize
# Required-Start:    $local_fs
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Expand root partition/filesystem on first boot
### END INIT INFO

case "$1" in
    start|restart|force-reload)
        /usr/sbin/rootfs-resize || true
        ;;
    stop)
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0
