BB_CONF_FRAGMENT_SUMMARY = "Ankaios common build settings"
BB_CONF_FRAGMENT_DESCRIPTION = "Shared settings from kas-common.yml for all Ankaios bitbake-setup profiles."

CONF_VERSION = "2"
EXTRA_IMAGE_FEATURES ?= "allow-empty-password empty-root-password allow-root-login"
USER_CLASSES ?= "buildstats"
PATCHRESOLVE = "noop"
BB_DISKMON_DIRS ??= " \
    STOPTASKS,${TMPDIR},1G,100K \
    STOPTASKS,${DL_DIR},1G,100K \
    STOPTASKS,${SSTATE_DIR},1G,100K \
    STOPTASKS,/tmp,100M,100K \
    HALT,${TMPDIR},100M,1K \
    HALT,${DL_DIR},100M,1K \
    HALT,${SSTATE_DIR},100M,1K \
    HALT,/tmp,10M,1K"

BB_HASHSERVE_UPSTREAM = "wss://hashserv.yoctoproject.org/ws"
SSTATE_MIRRORS ?= "file://.* http://sstate.yoctoproject.org/all/PATH;downloadfilename=PATH"
BB_HASHSERVE = "auto"
BB_SIGNATURE_HANDLER = "OEEquivHash"

DISTRO_FEATURES:append = " virtualization"

IMAGE_INSTALL:append = " curl"
IMAGE_INSTALL:append = " ankaios"
IMAGE_INSTALL:append = " podman"
IMAGE_INSTALL:append = " kernel-module-xt-multiport"

# On Raspberry Pi, expand root partition/filesystem to full SD card at first boot.
IMAGE_INSTALL:append:raspberrypi4-64 = " ankaios-rpi-rootfs-resize"
IMAGE_INSTALL:append:raspberrypi5 = " ankaios-rpi-rootfs-resize"