BB_CONF_FRAGMENT_SUMMARY = "Ankaios with systemd"
BB_CONF_FRAGMENT_DESCRIPTION = "Settings equivalent to kas-full-cmd-systemd.yml on top of shared Ankaios defaults."

require conf/fragments/ankaios/common.conf

DISTRO_FEATURES:append = " systemd usrmerge"

VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = "systemd-compat-units"

IMAGE_INSTALL:append = " tmux"
