BB_CONF_FRAGMENT_SUMMARY = "Ankaios with systemd"
BB_CONF_FRAGMENT_DESCRIPTION = "Settings equivalent to kas-full-cmd-systemd.yml on top of shared Ankaios defaults."

require conf/fragments/ankaios/common.conf

DISTRO_FEATURES:append = " systemd usrmerge"
DISTRO_FEATURES:remove = "sysvinit"

VIRTUAL-RUNTIME_init_manager = "systemd"

IMAGE_INSTALL:append = " tmux"
